CREATE TABLE dbo.Employee_Resumes
(
	Id INT PRIMARY KEY IDENTITY,
	EmpId INT NOT NULL FOREIGN KEY REFERENCES Employee_Login(Id),
	Summary VARCHAR(MAX) NULL,
	Experience INT  NULL,
	KeySkillsId UNIQUEIDENTIFIER NULL,
	WorkHistoryId UNIQUEIDENTIFIER NULL,
	EducationId UNIQUEIDENTIFIER NULL,
	CertificationId UNIQUEIDENTIFIER NULL,
)

