
CREATE TABLE dbo.Employee_Associations_Clubs
(
	Id UNIQUEIDENTIFIER NOT NULL,
	EmpId INT NOT NULL FOREIGN KEY REFERENCES Employee_Login(Id),
	Name VARCHAR(100) NOT NULL,
	StartDate DATETIME NOT NULL
	PRIMARY KEY CLUSTERED (Id, Name)
)