//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearch.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Education
    {
        public System.Guid Id { get; set; }
        public int EmpId { get; set; }
        public string University { get; set; }
        public System.DateTime GraduationDate { get; set; }
        public string Degree { get; set; }
    
        public virtual Employee_Login Employee_Login { get; set; }
    }
}
