//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearch.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Details
    {
        public int Id { get; set; }
        public int LoginId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public int JobTitleId { get; set; }
        public System.DateTime SignUpDate { get; set; }
    
        public virtual Job_Type Job_Type { get; set; }
        public virtual Employee_Login Employee_Login { get; set; }
    }
}
