//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearch.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Key_Skills
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public int ResumeId { get; set; }
    
        public virtual Employee_Resumes Employee_Resumes { get; set; }
    }
}
