//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearch.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Resumes
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        public string Summary { get; set; }
        public Nullable<int> Experience { get; set; }
        public Nullable<System.Guid> KeySkillsId { get; set; }
        public Nullable<System.Guid> WorkHistoryId { get; set; }
        public Nullable<System.Guid> EducationId { get; set; }
        public Nullable<System.Guid> CertificationId { get; set; }
    
        public virtual Employee_Login Employee_Login { get; set; }
    }
}
