//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearch.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Details
    {
        public int Id { get; set; }
        public Nullable<int> JobId { get; set; }
        public string JobDescription { get; set; }
        public Nullable<decimal> SalaryMin { get; set; }
        public Nullable<decimal> SalaryMax { get; set; }
        public int SalaryType { get; set; }
        public Nullable<int> MinWorkAuthorization { get; set; }
    
        public virtual Salary_Type Salary_Type { get; set; }
        public virtual Work_Authorization_Type Work_Authorization_Type { get; set; }
        public virtual Jobs Jobs { get; set; }
    }
}
