//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearch.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jobs()
        {
            this.Job_Reviews = new HashSet<Job_Reviews>();
            this.Jobs_Applied = new HashSet<Jobs_Applied>();
            this.Jobs_Hired = new HashSet<Jobs_Hired>();
            this.Employee_Login = new HashSet<Employee_Login>();
        }
    
        public int Id { get; set; }
        public string JobName { get; set; }
        public int JobTypeId { get; set; }
        public int CompanyId { get; set; }
        public string JobDescription { get; set; }
        public System.DateTime DatePosted { get; set; }
    
        public virtual Companies Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job_Reviews> Job_Reviews { get; set; }
        public virtual Job_Type Job_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jobs_Applied> Jobs_Applied { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jobs_Hired> Jobs_Hired { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Login> Employee_Login { get; set; }
    }
}
