//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearch.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location_Address
    {
        public int Id { get; set; }
        public string Street { get; set; }
        public int ZipCode { get; set; }
        public int City { get; set; }
        public int State { get; set; }
        public int Country { get; set; }
        public System.Guid UniqueId { get; set; }
    
        public virtual Reference_Country Reference_Country { get; set; }
        public virtual Reference_State Reference_State { get; set; }
        public virtual Reference_City Reference_City { get; set; }
    }
}
